### ISSUE TITLE
just setup fails as Firestore database already exists

### ISSUE THREAD

**Issue by gregoryfoster** [CouncilDataProject/cookiecutter-cdp-deployment#146]
### Describe the Bug

During initial setup of an instance, running `just setup [infrastructure_slug] [gcp_region]` resulted in a fatal error indicating the Firestore database already existed.

```bash
ERROR: (gcloud.firestore.databases.create) Resource in projects [infrastructure_slug] is the subject of a conflict: Database already exists. Please use another database_id
error: Recipe `setup` failed on line 76 with exit code 1
```

Commenting out that line, and the preceding lines that had been executed once already, enabled the setup script to continue without error.  I'm not sure where that `Justfile` is in this project, perhaps it's pulled in from elsewhere?  But it's in the generated instance directory under `SETUP/Justfile` line 76.

```bash
gcloud firestore databases create --location=us-west1
```

### Expected Behavior

The best I can figure, maybe there was a change in the preceding command which creates that resource?

```bash
gcloud app create --region=us-west1
```
This one didn't make sense to me.

### Reproduction

Following the standard installation procedure.

### Environment

_Any additional information about your environment._

-   OS Version: _[e.g. macOS 11.3.1]_
-   Cookiecutter Version: _[e.g. 0.5.0]_

**Comment by evamaxfield** [comment]
> I'm not sure where that Justfile is in this project, perhaps it's pulled in from elsewhere? But it's in the generated instance directory under SETUP/Justfile line 76

It lives in `cdp-backend` here: https://github.com/CouncilDataProject/cdp-backend/blob/main/cdp_backend/infrastructure/Justfile

We used to use Pulumi and tried Terraform to have "versioned infrastructure as code" but due to the fact that both of those are dependent on the upstream Google team adding their resources as modules to those libraries / ecosystems, we always found we had to do really really hacky things to get them to work.

Instead we switched to the Justfile setup we have now so that we can literally ship all of the files we need to _with_ the `cdp-backend` library which is versioned and already handles distribution of updates + it's directly tied to the backend library.

---

Can I ask how you discovered this issue? Were you trying to setup an entirely new CDP instance? Or were you re-running commands for an old instance you wanted to clean or something?

**Comment by evamaxfield** [comment]
Having multiple firebase setups in the same account is totally fine. We use a single GCP account for all of the instances that we maintain.

I think this is the second attempt to set on up issue.

If you go to the firebase console _is everything actually setup already even though the command failed_?

If that is the case, there might be a potential solution to this but sort of annoying one.

`Just` has a mechanism for "allow command to fail but keep moving on" -- we could make a second just command like `just retry-setup` which just has all of the same commands as `just setup` but marks them as "allowed fail" you can do this with:

`-some command here` (prepending the `-` to the command)

That might work but honestly there is just a whole host of issues that can happen in deployment sadly :(

**Comment by gregoryfoster** [comment]
I don't think we have enough to go on here, but it may be helpful to have it documented in the future.  Closing for now.
