### ISSUE TITLE
[Instance]: Alameda

### ISSUE THREAD

**Issue by phildini** [CouncilDataProject/cookiecutter-cdp-deployment#78]
### Municipality Name

The City of Alameda

### Governing Body Type

city council

### Maintainer GitHub Name

phildini

### Legistar Client Id

alameda

### Municipality Timezone

America/Los_Angeles

### Municipality Slug

alameda

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

_edit by @JacksonMaxfield, testing if this instance can be deployed with new LegistarScraper setup_

**Comment by JacksonMaxfield** [comment]
Hey @phildini Thanks for opening this issue! Excited at the potential for deploying in Alameda!

I am attempting to rerun the bot just to see if we get the weird `city_council` bug again, but on inspection of the actual data, the original bot report of "we have everything we need except the video links" does seem accurate.

Here is the data we received from Legistar for the last month of meetings for example: [alameda.md -- JSON blob as markdown because GitHub can't handle JSON upload](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/files/8100040/alameda.md)

What that basically means is: we can easily pull information about the event dates and times, the minutes items, the body, and a few more items.

Interestingly, I don't think the Alameda Legistar stores voting records or councilmember information. Which is quite frustrating because even after a few minutes of searching I can't find **_any_** city council voting records for Alameda. What is with cities and not having council member voting records easily accessible. :exploding_head: 

The big item that is missing is the "video link" but I see that Alameda follows the same pattern as our existing King County deployment which is basically: "Legistar data includes a link to the "event page" and the event page has a link to the "video page" and you can get the video from there.

Example:
* here is an event page in Legistar: https://alameda.legistar.com/MeetingDetail.aspx?ID=921005&GUID=92670E6E-2BB4-42CB-B751-24842E78023F&Options=info|&Search=
* on that page it has a link to "Video" which goes to: http://alameda.granicus.com/player/clip/2912?view_id=6&redirect=true
* on that page it has a direct video download with a URL that is easily accessible of: http://archive-media.granicus.com:443/OnDemand/alameda/alameda_16d3de22-7107-46f1-8f2e-cd64f390a6fd.mp4

Our King County scraper does basically that process and you can see that code here: https://github.com/CouncilDataProject/cdp-scrapers/blob/main/cdp_scrapers/instances/kingcounty.py#L83

---

Why am I telling you all of this:

If you want to deploy a CDP instance for Alameda and for us to cover it, you would need to basically fill in that function I linked for King County but for Alameda.

Once that is done, we can deploy a new instance of CDP for Alameda which would have:
* transcripts
* videos
* plain text search of meetings
* minutes items
* legislation details

but it would be missing:
* person info
* person voting records
* legislative status updates (but because of how we store legislative details, you could _kind of_ get this with the "legislation details")

All in all, Alameda should be decently easy to spin up and get running if you are interested in making the scraper and CDP would definitely be able to host and help get you setup.

Let me know what you think and thanks for even stopping by and making an issue!

**Comment by phildini** [comment]
Hey! Thanks for getting back to me.

So, hilariously, they keep the votes in the PDF of the minutes (see "Minutes" doc linked [here](https://alameda.legistar.com/MeetingDetail.aspx?ID=915896&GUID=D7A6F3A3-A9B1-4EE0-9227-68B2B0F0DE08&Options=info|&Search=)) but they don't put them into Legistar, I bet because they don't know _how_

I'm happy to take a stab at making the scraper, where would I make a PR for that?

**Comment by JacksonMaxfield** [comment]
@phildini due to some recent work by @dphoria, we can now fully deploy this with ease. Are you still interested? I can fully deploy it later today.

**Comment by phildini** [comment]
I am _definitely_ still interested.

**Comment by JacksonMaxfield** [comment]
Will attempt to deploy later today then!

**Comment by JacksonMaxfield** [comment]
Deployment Status - Complete

Website: https://councildataproject.org/alameda
Initial Data Backfill (just the last couple of days): https://github.com/CouncilDataProject/alameda/runs/6632548845?check_suite_focus=true

Data backfill should finish processing in an hour or so. Feel free to backfill more data if you would like to.

**Comment by JacksonMaxfield** [comment]
Highly recommend reading the: [admin-docs](https://github.com/CouncilDataProject/alameda/tree/main/admin-docs) for further setup / customization.

**Comment by phildini** [comment]
Beautiful, thank you! I'll review soon.

**Comment by JacksonMaxfield** [comment]
Seems like you may want to add a couple of "ignore minutes item patterns" to the scraper init: https://github.com/CouncilDataProject/alameda/blob/main/python/cdp_alameda_backend/scraper.py#L18

`LegistarScraper` docstring: https://github.com/CouncilDataProject/cdp-scrapers/blob/main/cdp_scrapers/legistar_utils.py#L567

![image](https://user-images.githubusercontent.com/17132317/170800730-4f0a3e06-4869-473c-9a8a-8715f09c76a7.png)

From: https://councildataproject.org/alameda/#/events/9ebe703133a0
